/*
 * Copyright (c) 2021 by the OnMetal authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dpdk.proto

package dpdkproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InterfaceType int32

const (
	InterfaceType_VirtualInterface   InterfaceType = 0
	InterfaceType_BareMetalInterface InterfaceType = 1
)

var InterfaceType_name = map[int32]string{
	0: "VirtualInterface",
	1: "BareMetalInterface",
}

var InterfaceType_value = map[string]int32{
	"VirtualInterface":   0,
	"BareMetalInterface": 1,
}

func (x InterfaceType) String() string {
	return proto.EnumName(InterfaceType_name, int32(x))
}

func (InterfaceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{0}
}

type IPVersion int32

const (
	IPVersion_IPv4 IPVersion = 0
	IPVersion_IPv6 IPVersion = 1
)

var IPVersion_name = map[int32]string{
	0: "IPv4",
	1: "IPv6",
}

var IPVersion_value = map[string]int32{
	"IPv4": 0,
	"IPv6": 1,
}

func (x IPVersion) String() string {
	return proto.EnumName(IPVersion_name, int32(x))
}

func (IPVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{1}
}

type Protocol int32

const (
	Protocol_Undefined Protocol = 0
	Protocol_ICMP      Protocol = 1
	Protocol_TCP       Protocol = 6
	Protocol_UDP       Protocol = 17
	Protocol_ICMPv6    Protocol = 58
	Protocol_SCTP      Protocol = 132
)

var Protocol_name = map[int32]string{
	0:   "Undefined",
	1:   "ICMP",
	6:   "TCP",
	17:  "UDP",
	58:  "ICMPv6",
	132: "SCTP",
}

var Protocol_value = map[string]int32{
	"Undefined": 0,
	"ICMP":      1,
	"TCP":       6,
	"UDP":       17,
	"ICMPv6":    58,
	"SCTP":      132,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}

func (Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{2}
}

type TrafficDirection int32

const (
	TrafficDirection_Ingress TrafficDirection = 0
	TrafficDirection_Egress  TrafficDirection = 1
)

var TrafficDirection_name = map[int32]string{
	0: "Ingress",
	1: "Egress",
}

var TrafficDirection_value = map[string]int32{
	"Ingress": 0,
	"Egress":  1,
}

func (x TrafficDirection) String() string {
	return proto.EnumName(TrafficDirection_name, int32(x))
}

func (TrafficDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{3}
}

type FirewallAction int32

const (
	FirewallAction_Drop   FirewallAction = 0
	FirewallAction_Accept FirewallAction = 1
)

var FirewallAction_name = map[int32]string{
	0: "Drop",
	1: "Accept",
}

var FirewallAction_value = map[string]int32{
	"Drop":   0,
	"Accept": 1,
}

func (x FirewallAction) String() string {
	return proto.EnumName(FirewallAction_name, int32(x))
}

func (FirewallAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{4}
}

type Status struct {
	Error                int32    `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type IpAdditionResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UnderlayRoute        []byte   `protobuf:"bytes,2,opt,name=underlayRoute,proto3" json:"underlayRoute,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IpAdditionResponse) Reset()         { *m = IpAdditionResponse{} }
func (m *IpAdditionResponse) String() string { return proto.CompactTextString(m) }
func (*IpAdditionResponse) ProtoMessage()    {}
func (*IpAdditionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{1}
}

func (m *IpAdditionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpAdditionResponse.Unmarshal(m, b)
}
func (m *IpAdditionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpAdditionResponse.Marshal(b, m, deterministic)
}
func (m *IpAdditionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpAdditionResponse.Merge(m, src)
}
func (m *IpAdditionResponse) XXX_Size() int {
	return xxx_messageInfo_IpAdditionResponse.Size(m)
}
func (m *IpAdditionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IpAdditionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IpAdditionResponse proto.InternalMessageInfo

func (m *IpAdditionResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *IpAdditionResponse) GetUnderlayRoute() []byte {
	if m != nil {
		return m.UnderlayRoute
	}
	return nil
}

type CreateLoadBalancerResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UnderlayRoute        []byte   `protobuf:"bytes,2,opt,name=underlayRoute,proto3" json:"underlayRoute,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLoadBalancerResponse) Reset()         { *m = CreateLoadBalancerResponse{} }
func (m *CreateLoadBalancerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLoadBalancerResponse) ProtoMessage()    {}
func (*CreateLoadBalancerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{2}
}

func (m *CreateLoadBalancerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLoadBalancerResponse.Unmarshal(m, b)
}
func (m *CreateLoadBalancerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLoadBalancerResponse.Marshal(b, m, deterministic)
}
func (m *CreateLoadBalancerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLoadBalancerResponse.Merge(m, src)
}
func (m *CreateLoadBalancerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLoadBalancerResponse.Size(m)
}
func (m *CreateLoadBalancerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLoadBalancerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLoadBalancerResponse proto.InternalMessageInfo

func (m *CreateLoadBalancerResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreateLoadBalancerResponse) GetUnderlayRoute() []byte {
	if m != nil {
		return m.UnderlayRoute
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Prefix struct {
	IpVersion            IPVersion `protobuf:"varint,1,opt,name=ipVersion,proto3,enum=dpdkonmetal.IPVersion" json:"ipVersion,omitempty"`
	Address              []byte    `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PrefixLength         uint32    `protobuf:"varint,3,opt,name=prefixLength,proto3" json:"prefixLength,omitempty"`
	LoadBalancerEnabled  bool      `protobuf:"varint,4,opt,name=loadBalancerEnabled,proto3" json:"loadBalancerEnabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Prefix) Reset()         { *m = Prefix{} }
func (m *Prefix) String() string { return proto.CompactTextString(m) }
func (*Prefix) ProtoMessage()    {}
func (*Prefix) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{4}
}

func (m *Prefix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prefix.Unmarshal(m, b)
}
func (m *Prefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prefix.Marshal(b, m, deterministic)
}
func (m *Prefix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prefix.Merge(m, src)
}
func (m *Prefix) XXX_Size() int {
	return xxx_messageInfo_Prefix.Size(m)
}
func (m *Prefix) XXX_DiscardUnknown() {
	xxx_messageInfo_Prefix.DiscardUnknown(m)
}

var xxx_messageInfo_Prefix proto.InternalMessageInfo

func (m *Prefix) GetIpVersion() IPVersion {
	if m != nil {
		return m.IpVersion
	}
	return IPVersion_IPv4
}

func (m *Prefix) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Prefix) GetPrefixLength() uint32 {
	if m != nil {
		return m.PrefixLength
	}
	return 0
}

func (m *Prefix) GetLoadBalancerEnabled() bool {
	if m != nil {
		return m.LoadBalancerEnabled
	}
	return false
}

type InitConfig struct {
	UnderlayIPv6Prefix   *Prefix  `protobuf:"bytes,1,opt,name=underlayIPv6Prefix,proto3" json:"underlayIPv6Prefix,omitempty"`
	UplinkPorts          []string `protobuf:"bytes,2,rep,name=uplinkPorts,proto3" json:"uplinkPorts,omitempty"`
	PfNames              []string `protobuf:"bytes,3,rep,name=pfNames,proto3" json:"pfNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitConfig) Reset()         { *m = InitConfig{} }
func (m *InitConfig) String() string { return proto.CompactTextString(m) }
func (*InitConfig) ProtoMessage()    {}
func (*InitConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{5}
}

func (m *InitConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitConfig.Unmarshal(m, b)
}
func (m *InitConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitConfig.Marshal(b, m, deterministic)
}
func (m *InitConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitConfig.Merge(m, src)
}
func (m *InitConfig) XXX_Size() int {
	return xxx_messageInfo_InitConfig.Size(m)
}
func (m *InitConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_InitConfig.DiscardUnknown(m)
}

var xxx_messageInfo_InitConfig proto.InternalMessageInfo

func (m *InitConfig) GetUnderlayIPv6Prefix() *Prefix {
	if m != nil {
		return m.UnderlayIPv6Prefix
	}
	return nil
}

func (m *InitConfig) GetUplinkPorts() []string {
	if m != nil {
		return m.UplinkPorts
	}
	return nil
}

func (m *InitConfig) GetPfNames() []string {
	if m != nil {
		return m.PfNames
	}
	return nil
}

type PXEConfig struct {
	NextServer           string   `protobuf:"bytes,1,opt,name=nextServer,proto3" json:"nextServer,omitempty"`
	BootFileName         string   `protobuf:"bytes,2,opt,name=bootFileName,proto3" json:"bootFileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PXEConfig) Reset()         { *m = PXEConfig{} }
func (m *PXEConfig) String() string { return proto.CompactTextString(m) }
func (*PXEConfig) ProtoMessage()    {}
func (*PXEConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{6}
}

func (m *PXEConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PXEConfig.Unmarshal(m, b)
}
func (m *PXEConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PXEConfig.Marshal(b, m, deterministic)
}
func (m *PXEConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PXEConfig.Merge(m, src)
}
func (m *PXEConfig) XXX_Size() int {
	return xxx_messageInfo_PXEConfig.Size(m)
}
func (m *PXEConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PXEConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PXEConfig proto.InternalMessageInfo

func (m *PXEConfig) GetNextServer() string {
	if m != nil {
		return m.NextServer
	}
	return ""
}

func (m *PXEConfig) GetBootFileName() string {
	if m != nil {
		return m.BootFileName
	}
	return ""
}

// Firewall Rules can be inserted and removed while the interface is running. In the C code probably it makes sense to use linked lists.
// Firewall rules have an order and may result in accepting or dropping a packet.
// When a packet matches a firewall rule, the defined action is taken. No further firewall rules will be evaluated thereafter.
type FirewallRule struct {
	// ruleID: UUID - empty when inserting new rule
	RuleID []byte `protobuf:"bytes,1,opt,name=ruleID,proto3" json:"ruleID,omitempty"`
	// insertAfterRuleID: UUID reference to next FirewallRule
	// used to define the order when inserting new rules
	// when 0 or empty, insert the rule on the firewall rules list's first position
	InsertAfterRuleID []byte           `protobuf:"bytes,2,opt,name=insertAfterRuleID,proto3" json:"insertAfterRuleID,omitempty"`
	Direction         TrafficDirection `protobuf:"varint,3,opt,name=direction,proto3,enum=dpdkonmetal.TrafficDirection" json:"direction,omitempty"`
	Action            FirewallAction   `protobuf:"varint,4,opt,name=action,proto3,enum=dpdkonmetal.FirewallAction" json:"action,omitempty"`
	IpVersion         IPVersion        `protobuf:"varint,5,opt,name=ipVersion,proto3,enum=dpdkonmetal.IPVersion" json:"ipVersion,omitempty"`
	SourcePrefix      *Prefix          `protobuf:"bytes,6,opt,name=sourcePrefix,proto3" json:"sourcePrefix,omitempty"`
	DestinationPrefix *Prefix          `protobuf:"bytes,7,opt,name=destinationPrefix,proto3" json:"destinationPrefix,omitempty"`
	Protocol          Protocol         `protobuf:"varint,8,opt,name=protocol,proto3,enum=dpdkonmetal.Protocol" json:"protocol,omitempty"`
	// TCP / UDP / SCTP filters
	SourcePortRangeLower      int32 `protobuf:"varint,9,opt,name=sourcePortRangeLower,proto3" json:"sourcePortRangeLower,omitempty"`
	SourcePortRangeUpper      int32 `protobuf:"varint,10,opt,name=sourcePortRangeUpper,proto3" json:"sourcePortRangeUpper,omitempty"`
	DestinationPortRangeLower int32 `protobuf:"varint,11,opt,name=destinationPortRangeLower,proto3" json:"destinationPortRangeLower,omitempty"`
	DestinationPortRangeUpper int32 `protobuf:"varint,12,opt,name=destinationPortRangeUpper,proto3" json:"destinationPortRangeUpper,omitempty"`
	// ICMP filters
	IcmpCode             int32    `protobuf:"varint,13,opt,name=icmpCode,proto3" json:"icmpCode,omitempty"`
	IcmpType             int32    `protobuf:"varint,14,opt,name=icmpType,proto3" json:"icmpType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirewallRule) Reset()         { *m = FirewallRule{} }
func (m *FirewallRule) String() string { return proto.CompactTextString(m) }
func (*FirewallRule) ProtoMessage()    {}
func (*FirewallRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{7}
}

func (m *FirewallRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirewallRule.Unmarshal(m, b)
}
func (m *FirewallRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirewallRule.Marshal(b, m, deterministic)
}
func (m *FirewallRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirewallRule.Merge(m, src)
}
func (m *FirewallRule) XXX_Size() int {
	return xxx_messageInfo_FirewallRule.Size(m)
}
func (m *FirewallRule) XXX_DiscardUnknown() {
	xxx_messageInfo_FirewallRule.DiscardUnknown(m)
}

var xxx_messageInfo_FirewallRule proto.InternalMessageInfo

func (m *FirewallRule) GetRuleID() []byte {
	if m != nil {
		return m.RuleID
	}
	return nil
}

func (m *FirewallRule) GetInsertAfterRuleID() []byte {
	if m != nil {
		return m.InsertAfterRuleID
	}
	return nil
}

func (m *FirewallRule) GetDirection() TrafficDirection {
	if m != nil {
		return m.Direction
	}
	return TrafficDirection_Ingress
}

func (m *FirewallRule) GetAction() FirewallAction {
	if m != nil {
		return m.Action
	}
	return FirewallAction_Drop
}

func (m *FirewallRule) GetIpVersion() IPVersion {
	if m != nil {
		return m.IpVersion
	}
	return IPVersion_IPv4
}

func (m *FirewallRule) GetSourcePrefix() *Prefix {
	if m != nil {
		return m.SourcePrefix
	}
	return nil
}

func (m *FirewallRule) GetDestinationPrefix() *Prefix {
	if m != nil {
		return m.DestinationPrefix
	}
	return nil
}

func (m *FirewallRule) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_Undefined
}

func (m *FirewallRule) GetSourcePortRangeLower() int32 {
	if m != nil {
		return m.SourcePortRangeLower
	}
	return 0
}

func (m *FirewallRule) GetSourcePortRangeUpper() int32 {
	if m != nil {
		return m.SourcePortRangeUpper
	}
	return 0
}

func (m *FirewallRule) GetDestinationPortRangeLower() int32 {
	if m != nil {
		return m.DestinationPortRangeLower
	}
	return 0
}

func (m *FirewallRule) GetDestinationPortRangeUpper() int32 {
	if m != nil {
		return m.DestinationPortRangeUpper
	}
	return 0
}

func (m *FirewallRule) GetIcmpCode() int32 {
	if m != nil {
		return m.IcmpCode
	}
	return 0
}

func (m *FirewallRule) GetIcmpType() int32 {
	if m != nil {
		return m.IcmpType
	}
	return 0
}

type IPConfig struct {
	IpVersion IPVersion `protobuf:"varint,1,opt,name=ipVersion,proto3,enum=dpdkonmetal.IPVersion" json:"ipVersion,omitempty"`
	// DHCP Options
	PrimaryAddress       []byte          `protobuf:"bytes,2,opt,name=primaryAddress,proto3" json:"primaryAddress,omitempty"`
	Mtu                  uint32          `protobuf:"varint,3,opt,name=mtu,proto3" json:"mtu,omitempty"`
	DhcpHostname         string          `protobuf:"bytes,4,opt,name=dhcpHostname,proto3" json:"dhcpHostname,omitempty"`
	DhcpDomainname       string          `protobuf:"bytes,5,opt,name=dhcpDomainname,proto3" json:"dhcpDomainname,omitempty"`
	PxeConfig            *PXEConfig      `protobuf:"bytes,6,opt,name=pxeConfig,proto3" json:"pxeConfig,omitempty"`
	Ntp                  []string        `protobuf:"bytes,7,rep,name=ntp,proto3" json:"ntp,omitempty"`
	Dns                  [][]byte        `protobuf:"bytes,8,rep,name=dns,proto3" json:"dns,omitempty"`
	FirewallRules        []*FirewallRule `protobuf:"bytes,9,rep,name=firewallRules,proto3" json:"firewallRules,omitempty"`
	InterfacePrefixes    []*Prefix       `protobuf:"bytes,10,rep,name=interfacePrefixes,proto3" json:"interfacePrefixes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *IPConfig) Reset()         { *m = IPConfig{} }
func (m *IPConfig) String() string { return proto.CompactTextString(m) }
func (*IPConfig) ProtoMessage()    {}
func (*IPConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{8}
}

func (m *IPConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPConfig.Unmarshal(m, b)
}
func (m *IPConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPConfig.Marshal(b, m, deterministic)
}
func (m *IPConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPConfig.Merge(m, src)
}
func (m *IPConfig) XXX_Size() int {
	return xxx_messageInfo_IPConfig.Size(m)
}
func (m *IPConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IPConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IPConfig proto.InternalMessageInfo

func (m *IPConfig) GetIpVersion() IPVersion {
	if m != nil {
		return m.IpVersion
	}
	return IPVersion_IPv4
}

func (m *IPConfig) GetPrimaryAddress() []byte {
	if m != nil {
		return m.PrimaryAddress
	}
	return nil
}

func (m *IPConfig) GetMtu() uint32 {
	if m != nil {
		return m.Mtu
	}
	return 0
}

func (m *IPConfig) GetDhcpHostname() string {
	if m != nil {
		return m.DhcpHostname
	}
	return ""
}

func (m *IPConfig) GetDhcpDomainname() string {
	if m != nil {
		return m.DhcpDomainname
	}
	return ""
}

func (m *IPConfig) GetPxeConfig() *PXEConfig {
	if m != nil {
		return m.PxeConfig
	}
	return nil
}

func (m *IPConfig) GetNtp() []string {
	if m != nil {
		return m.Ntp
	}
	return nil
}

func (m *IPConfig) GetDns() [][]byte {
	if m != nil {
		return m.Dns
	}
	return nil
}

func (m *IPConfig) GetFirewallRules() []*FirewallRule {
	if m != nil {
		return m.FirewallRules
	}
	return nil
}

func (m *IPConfig) GetInterfacePrefixes() []*Prefix {
	if m != nil {
		return m.InterfacePrefixes
	}
	return nil
}

type ThrottlingConfig struct {
	IngressPacketsPerSecond  uint32   `protobuf:"varint,1,opt,name=ingressPacketsPerSecond,proto3" json:"ingressPacketsPerSecond,omitempty"`
	IngressMegabitsPerSecond uint32   `protobuf:"varint,2,opt,name=ingressMegabitsPerSecond,proto3" json:"ingressMegabitsPerSecond,omitempty"`
	EgressPacketsPerSecond   uint32   `protobuf:"varint,3,opt,name=egressPacketsPerSecond,proto3" json:"egressPacketsPerSecond,omitempty"`
	EgressMegabitsPerSecond  uint32   `protobuf:"varint,4,opt,name=egressMegabitsPerSecond,proto3" json:"egressMegabitsPerSecond,omitempty"`
	MaxOpenFlows             uint32   `protobuf:"varint,5,opt,name=maxOpenFlows,proto3" json:"maxOpenFlows,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *ThrottlingConfig) Reset()         { *m = ThrottlingConfig{} }
func (m *ThrottlingConfig) String() string { return proto.CompactTextString(m) }
func (*ThrottlingConfig) ProtoMessage()    {}
func (*ThrottlingConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{9}
}

func (m *ThrottlingConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThrottlingConfig.Unmarshal(m, b)
}
func (m *ThrottlingConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThrottlingConfig.Marshal(b, m, deterministic)
}
func (m *ThrottlingConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThrottlingConfig.Merge(m, src)
}
func (m *ThrottlingConfig) XXX_Size() int {
	return xxx_messageInfo_ThrottlingConfig.Size(m)
}
func (m *ThrottlingConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ThrottlingConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ThrottlingConfig proto.InternalMessageInfo

func (m *ThrottlingConfig) GetIngressPacketsPerSecond() uint32 {
	if m != nil {
		return m.IngressPacketsPerSecond
	}
	return 0
}

func (m *ThrottlingConfig) GetIngressMegabitsPerSecond() uint32 {
	if m != nil {
		return m.IngressMegabitsPerSecond
	}
	return 0
}

func (m *ThrottlingConfig) GetEgressPacketsPerSecond() uint32 {
	if m != nil {
		return m.EgressPacketsPerSecond
	}
	return 0
}

func (m *ThrottlingConfig) GetEgressMegabitsPerSecond() uint32 {
	if m != nil {
		return m.EgressMegabitsPerSecond
	}
	return 0
}

func (m *ThrottlingConfig) GetMaxOpenFlows() uint32 {
	if m != nil {
		return m.MaxOpenFlows
	}
	return 0
}

type CreateInterfaceRequest struct {
	// interfaceType defines whether a Bare Metal Interface or a Virtual Interface is created.
	// Both instance types cannot be mixed during a session.
	// Maximum number of instantiated bare metal interfaces is 1.
	// Maximum number of Virtual Interfaces is not defined.
	// If you specify device name, a device with this name will be assigned, if it exists
	// otherwise an error code. If you dont specify any device name, next available VF
	// will be assigned.
	InterfaceType        InterfaceType     `protobuf:"varint,1,opt,name=interfaceType,proto3,enum=dpdkonmetal.InterfaceType" json:"interfaceType,omitempty"`
	InterfaceID          []byte            `protobuf:"bytes,2,opt,name=interfaceID,proto3" json:"interfaceID,omitempty"`
	Vni                  uint32            `protobuf:"varint,3,opt,name=vni,proto3" json:"vni,omitempty"`
	Ipv4Config           *IPConfig         `protobuf:"bytes,4,opt,name=ipv4Config,proto3" json:"ipv4Config,omitempty"`
	Ipv6Config           *IPConfig         `protobuf:"bytes,5,opt,name=ipv6Config,proto3" json:"ipv6Config,omitempty"`
	DeviceName           string            `protobuf:"bytes,6,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	ThrottlingConfig     *ThrottlingConfig `protobuf:"bytes,7,opt,name=throttlingConfig,proto3" json:"throttlingConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateInterfaceRequest) Reset()         { *m = CreateInterfaceRequest{} }
func (m *CreateInterfaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateInterfaceRequest) ProtoMessage()    {}
func (*CreateInterfaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{10}
}

func (m *CreateInterfaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInterfaceRequest.Unmarshal(m, b)
}
func (m *CreateInterfaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInterfaceRequest.Marshal(b, m, deterministic)
}
func (m *CreateInterfaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInterfaceRequest.Merge(m, src)
}
func (m *CreateInterfaceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateInterfaceRequest.Size(m)
}
func (m *CreateInterfaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInterfaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInterfaceRequest proto.InternalMessageInfo

func (m *CreateInterfaceRequest) GetInterfaceType() InterfaceType {
	if m != nil {
		return m.InterfaceType
	}
	return InterfaceType_VirtualInterface
}

func (m *CreateInterfaceRequest) GetInterfaceID() []byte {
	if m != nil {
		return m.InterfaceID
	}
	return nil
}

func (m *CreateInterfaceRequest) GetVni() uint32 {
	if m != nil {
		return m.Vni
	}
	return 0
}

func (m *CreateInterfaceRequest) GetIpv4Config() *IPConfig {
	if m != nil {
		return m.Ipv4Config
	}
	return nil
}

func (m *CreateInterfaceRequest) GetIpv6Config() *IPConfig {
	if m != nil {
		return m.Ipv6Config
	}
	return nil
}

func (m *CreateInterfaceRequest) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *CreateInterfaceRequest) GetThrottlingConfig() *ThrottlingConfig {
	if m != nil {
		return m.ThrottlingConfig
	}
	return nil
}

type Interface struct {
	InterfaceID          []byte            `protobuf:"bytes,1,opt,name=interfaceID,proto3" json:"interfaceID,omitempty"`
	Vni                  uint32            `protobuf:"varint,2,opt,name=vni,proto3" json:"vni,omitempty"`
	PrimaryIPv4Address   []byte            `protobuf:"bytes,3,opt,name=primaryIPv4Address,proto3" json:"primaryIPv4Address,omitempty"`
	PrimaryIPv6Address   []byte            `protobuf:"bytes,4,opt,name=primaryIPv6Address,proto3" json:"primaryIPv6Address,omitempty"`
	ThrottlingConfig     *ThrottlingConfig `protobuf:"bytes,5,opt,name=throttlingConfig,proto3" json:"throttlingConfig,omitempty"`
	UnderlayRoute        []byte            `protobuf:"bytes,6,opt,name=underlayRoute,proto3" json:"underlayRoute,omitempty"`
	PciDpName            string            `protobuf:"bytes,7,opt,name=pciDpName,proto3" json:"pciDpName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Interface) Reset()         { *m = Interface{} }
func (m *Interface) String() string { return proto.CompactTextString(m) }
func (*Interface) ProtoMessage()    {}
func (*Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{11}
}

func (m *Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interface.Unmarshal(m, b)
}
func (m *Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interface.Marshal(b, m, deterministic)
}
func (m *Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interface.Merge(m, src)
}
func (m *Interface) XXX_Size() int {
	return xxx_messageInfo_Interface.Size(m)
}
func (m *Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_Interface proto.InternalMessageInfo

func (m *Interface) GetInterfaceID() []byte {
	if m != nil {
		return m.InterfaceID
	}
	return nil
}

func (m *Interface) GetVni() uint32 {
	if m != nil {
		return m.Vni
	}
	return 0
}

func (m *Interface) GetPrimaryIPv4Address() []byte {
	if m != nil {
		return m.PrimaryIPv4Address
	}
	return nil
}

func (m *Interface) GetPrimaryIPv6Address() []byte {
	if m != nil {
		return m.PrimaryIPv6Address
	}
	return nil
}

func (m *Interface) GetThrottlingConfig() *ThrottlingConfig {
	if m != nil {
		return m.ThrottlingConfig
	}
	return nil
}

func (m *Interface) GetUnderlayRoute() []byte {
	if m != nil {
		return m.UnderlayRoute
	}
	return nil
}

func (m *Interface) GetPciDpName() string {
	if m != nil {
		return m.PciDpName
	}
	return ""
}

type InterfaceIDMsg struct {
	InterfaceID          []byte   `protobuf:"bytes,1,opt,name=interfaceID,proto3" json:"interfaceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfaceIDMsg) Reset()         { *m = InterfaceIDMsg{} }
func (m *InterfaceIDMsg) String() string { return proto.CompactTextString(m) }
func (*InterfaceIDMsg) ProtoMessage()    {}
func (*InterfaceIDMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{12}
}

func (m *InterfaceIDMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceIDMsg.Unmarshal(m, b)
}
func (m *InterfaceIDMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceIDMsg.Marshal(b, m, deterministic)
}
func (m *InterfaceIDMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceIDMsg.Merge(m, src)
}
func (m *InterfaceIDMsg) XXX_Size() int {
	return xxx_messageInfo_InterfaceIDMsg.Size(m)
}
func (m *InterfaceIDMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceIDMsg.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceIDMsg proto.InternalMessageInfo

func (m *InterfaceIDMsg) GetInterfaceID() []byte {
	if m != nil {
		return m.InterfaceID
	}
	return nil
}

type GetInterfaceResponse struct {
	Status               *Status    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Interface            *Interface `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetInterfaceResponse) Reset()         { *m = GetInterfaceResponse{} }
func (m *GetInterfaceResponse) String() string { return proto.CompactTextString(m) }
func (*GetInterfaceResponse) ProtoMessage()    {}
func (*GetInterfaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{13}
}

func (m *GetInterfaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInterfaceResponse.Unmarshal(m, b)
}
func (m *GetInterfaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInterfaceResponse.Marshal(b, m, deterministic)
}
func (m *GetInterfaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInterfaceResponse.Merge(m, src)
}
func (m *GetInterfaceResponse) XXX_Size() int {
	return xxx_messageInfo_GetInterfaceResponse.Size(m)
}
func (m *GetInterfaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInterfaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInterfaceResponse proto.InternalMessageInfo

func (m *GetInterfaceResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetInterfaceResponse) GetInterface() *Interface {
	if m != nil {
		return m.Interface
	}
	return nil
}

type InterfaceVIPIP struct {
	Status               *Status   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IpVersion            IPVersion `protobuf:"varint,2,opt,name=ipVersion,proto3,enum=dpdkonmetal.IPVersion" json:"ipVersion,omitempty"`
	Address              []byte    `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *InterfaceVIPIP) Reset()         { *m = InterfaceVIPIP{} }
func (m *InterfaceVIPIP) String() string { return proto.CompactTextString(m) }
func (*InterfaceVIPIP) ProtoMessage()    {}
func (*InterfaceVIPIP) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{14}
}

func (m *InterfaceVIPIP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceVIPIP.Unmarshal(m, b)
}
func (m *InterfaceVIPIP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceVIPIP.Marshal(b, m, deterministic)
}
func (m *InterfaceVIPIP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceVIPIP.Merge(m, src)
}
func (m *InterfaceVIPIP) XXX_Size() int {
	return xxx_messageInfo_InterfaceVIPIP.Size(m)
}
func (m *InterfaceVIPIP) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceVIPIP.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceVIPIP proto.InternalMessageInfo

func (m *InterfaceVIPIP) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InterfaceVIPIP) GetIpVersion() IPVersion {
	if m != nil {
		return m.IpVersion
	}
	return IPVersion_IPv4
}

func (m *InterfaceVIPIP) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type LBIP struct {
	IpVersion            IPVersion `protobuf:"varint,1,opt,name=ipVersion,proto3,enum=dpdkonmetal.IPVersion" json:"ipVersion,omitempty"`
	Address              []byte    `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LBIP) Reset()         { *m = LBIP{} }
func (m *LBIP) String() string { return proto.CompactTextString(m) }
func (*LBIP) ProtoMessage()    {}
func (*LBIP) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{15}
}

func (m *LBIP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LBIP.Unmarshal(m, b)
}
func (m *LBIP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LBIP.Marshal(b, m, deterministic)
}
func (m *LBIP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LBIP.Merge(m, src)
}
func (m *LBIP) XXX_Size() int {
	return xxx_messageInfo_LBIP.Size(m)
}
func (m *LBIP) XXX_DiscardUnknown() {
	xxx_messageInfo_LBIP.DiscardUnknown(m)
}

var xxx_messageInfo_LBIP proto.InternalMessageInfo

func (m *LBIP) GetIpVersion() IPVersion {
	if m != nil {
		return m.IpVersion
	}
	return IPVersion_IPv4
}

func (m *LBIP) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type InterfaceVIPMsg struct {
	InterfaceID          []byte          `protobuf:"bytes,1,opt,name=interfaceID,proto3" json:"interfaceID,omitempty"`
	InterfaceVIPIP       *InterfaceVIPIP `protobuf:"bytes,2,opt,name=interfaceVIPIP,proto3" json:"interfaceVIPIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InterfaceVIPMsg) Reset()         { *m = InterfaceVIPMsg{} }
func (m *InterfaceVIPMsg) String() string { return proto.CompactTextString(m) }
func (*InterfaceVIPMsg) ProtoMessage()    {}
func (*InterfaceVIPMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{16}
}

func (m *InterfaceVIPMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceVIPMsg.Unmarshal(m, b)
}
func (m *InterfaceVIPMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceVIPMsg.Marshal(b, m, deterministic)
}
func (m *InterfaceVIPMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceVIPMsg.Merge(m, src)
}
func (m *InterfaceVIPMsg) XXX_Size() int {
	return xxx_messageInfo_InterfaceVIPMsg.Size(m)
}
func (m *InterfaceVIPMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceVIPMsg.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceVIPMsg proto.InternalMessageInfo

func (m *InterfaceVIPMsg) GetInterfaceID() []byte {
	if m != nil {
		return m.InterfaceID
	}
	return nil
}

func (m *InterfaceVIPMsg) GetInterfaceVIPIP() *InterfaceVIPIP {
	if m != nil {
		return m.InterfaceVIPIP
	}
	return nil
}

type GetLoadBalancerRequest struct {
	LoadBalancerID       []byte   `protobuf:"bytes,1,opt,name=loadBalancerID,proto3" json:"loadBalancerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLoadBalancerRequest) Reset()         { *m = GetLoadBalancerRequest{} }
func (m *GetLoadBalancerRequest) String() string { return proto.CompactTextString(m) }
func (*GetLoadBalancerRequest) ProtoMessage()    {}
func (*GetLoadBalancerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{17}
}

func (m *GetLoadBalancerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLoadBalancerRequest.Unmarshal(m, b)
}
func (m *GetLoadBalancerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLoadBalancerRequest.Marshal(b, m, deterministic)
}
func (m *GetLoadBalancerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLoadBalancerRequest.Merge(m, src)
}
func (m *GetLoadBalancerRequest) XXX_Size() int {
	return xxx_messageInfo_GetLoadBalancerRequest.Size(m)
}
func (m *GetLoadBalancerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLoadBalancerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLoadBalancerRequest proto.InternalMessageInfo

func (m *GetLoadBalancerRequest) GetLoadBalancerID() []byte {
	if m != nil {
		return m.LoadBalancerID
	}
	return nil
}

type GetLoadBalancerTargetsRequest struct {
	LoadBalancerID       []byte   `protobuf:"bytes,1,opt,name=loadBalancerID,proto3" json:"loadBalancerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLoadBalancerTargetsRequest) Reset()         { *m = GetLoadBalancerTargetsRequest{} }
func (m *GetLoadBalancerTargetsRequest) String() string { return proto.CompactTextString(m) }
func (*GetLoadBalancerTargetsRequest) ProtoMessage()    {}
func (*GetLoadBalancerTargetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{18}
}

func (m *GetLoadBalancerTargetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLoadBalancerTargetsRequest.Unmarshal(m, b)
}
func (m *GetLoadBalancerTargetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLoadBalancerTargetsRequest.Marshal(b, m, deterministic)
}
func (m *GetLoadBalancerTargetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLoadBalancerTargetsRequest.Merge(m, src)
}
func (m *GetLoadBalancerTargetsRequest) XXX_Size() int {
	return xxx_messageInfo_GetLoadBalancerTargetsRequest.Size(m)
}
func (m *GetLoadBalancerTargetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLoadBalancerTargetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLoadBalancerTargetsRequest proto.InternalMessageInfo

func (m *GetLoadBalancerTargetsRequest) GetLoadBalancerID() []byte {
	if m != nil {
		return m.LoadBalancerID
	}
	return nil
}

type DeleteLoadBalancerRequest struct {
	LoadBalancerID       []byte   `protobuf:"bytes,1,opt,name=loadBalancerID,proto3" json:"loadBalancerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLoadBalancerRequest) Reset()         { *m = DeleteLoadBalancerRequest{} }
func (m *DeleteLoadBalancerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLoadBalancerRequest) ProtoMessage()    {}
func (*DeleteLoadBalancerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{19}
}

func (m *DeleteLoadBalancerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLoadBalancerRequest.Unmarshal(m, b)
}
func (m *DeleteLoadBalancerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLoadBalancerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteLoadBalancerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLoadBalancerRequest.Merge(m, src)
}
func (m *DeleteLoadBalancerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLoadBalancerRequest.Size(m)
}
func (m *DeleteLoadBalancerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLoadBalancerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLoadBalancerRequest proto.InternalMessageInfo

func (m *DeleteLoadBalancerRequest) GetLoadBalancerID() []byte {
	if m != nil {
		return m.LoadBalancerID
	}
	return nil
}

type LBPort struct {
	Port                 uint32   `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Protocol             Protocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=dpdkonmetal.Protocol" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LBPort) Reset()         { *m = LBPort{} }
func (m *LBPort) String() string { return proto.CompactTextString(m) }
func (*LBPort) ProtoMessage()    {}
func (*LBPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{20}
}

func (m *LBPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LBPort.Unmarshal(m, b)
}
func (m *LBPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LBPort.Marshal(b, m, deterministic)
}
func (m *LBPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LBPort.Merge(m, src)
}
func (m *LBPort) XXX_Size() int {
	return xxx_messageInfo_LBPort.Size(m)
}
func (m *LBPort) XXX_DiscardUnknown() {
	xxx_messageInfo_LBPort.DiscardUnknown(m)
}

var xxx_messageInfo_LBPort proto.InternalMessageInfo

func (m *LBPort) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *LBPort) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_Undefined
}

type GetLoadBalancerTargetsResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TargetIPs            []*LBIP  `protobuf:"bytes,2,rep,name=targetIPs,proto3" json:"targetIPs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLoadBalancerTargetsResponse) Reset()         { *m = GetLoadBalancerTargetsResponse{} }
func (m *GetLoadBalancerTargetsResponse) String() string { return proto.CompactTextString(m) }
func (*GetLoadBalancerTargetsResponse) ProtoMessage()    {}
func (*GetLoadBalancerTargetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{21}
}

func (m *GetLoadBalancerTargetsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLoadBalancerTargetsResponse.Unmarshal(m, b)
}
func (m *GetLoadBalancerTargetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLoadBalancerTargetsResponse.Marshal(b, m, deterministic)
}
func (m *GetLoadBalancerTargetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLoadBalancerTargetsResponse.Merge(m, src)
}
func (m *GetLoadBalancerTargetsResponse) XXX_Size() int {
	return xxx_messageInfo_GetLoadBalancerTargetsResponse.Size(m)
}
func (m *GetLoadBalancerTargetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLoadBalancerTargetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLoadBalancerTargetsResponse proto.InternalMessageInfo

func (m *GetLoadBalancerTargetsResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetLoadBalancerTargetsResponse) GetTargetIPs() []*LBIP {
	if m != nil {
		return m.TargetIPs
	}
	return nil
}

type GetLoadBalancerResponse struct {
	Status               *Status   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	LbVipIP              *LBIP     `protobuf:"bytes,2,opt,name=lbVipIP,proto3" json:"lbVipIP,omitempty"`
	Vni                  uint32    `protobuf:"varint,3,opt,name=vni,proto3" json:"vni,omitempty"`
	Lbports              []*LBPort `protobuf:"bytes,4,rep,name=lbports,proto3" json:"lbports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetLoadBalancerResponse) Reset()         { *m = GetLoadBalancerResponse{} }
func (m *GetLoadBalancerResponse) String() string { return proto.CompactTextString(m) }
func (*GetLoadBalancerResponse) ProtoMessage()    {}
func (*GetLoadBalancerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{22}
}

func (m *GetLoadBalancerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLoadBalancerResponse.Unmarshal(m, b)
}
func (m *GetLoadBalancerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLoadBalancerResponse.Marshal(b, m, deterministic)
}
func (m *GetLoadBalancerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLoadBalancerResponse.Merge(m, src)
}
func (m *GetLoadBalancerResponse) XXX_Size() int {
	return xxx_messageInfo_GetLoadBalancerResponse.Size(m)
}
func (m *GetLoadBalancerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLoadBalancerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLoadBalancerResponse proto.InternalMessageInfo

func (m *GetLoadBalancerResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetLoadBalancerResponse) GetLbVipIP() *LBIP {
	if m != nil {
		return m.LbVipIP
	}
	return nil
}

func (m *GetLoadBalancerResponse) GetVni() uint32 {
	if m != nil {
		return m.Vni
	}
	return 0
}

func (m *GetLoadBalancerResponse) GetLbports() []*LBPort {
	if m != nil {
		return m.Lbports
	}
	return nil
}

type CreateLoadBalancerRequest struct {
	LoadBalancerID       []byte    `protobuf:"bytes,1,opt,name=loadBalancerID,proto3" json:"loadBalancerID,omitempty"`
	LbVipIP              *LBIP     `protobuf:"bytes,2,opt,name=lbVipIP,proto3" json:"lbVipIP,omitempty"`
	Vni                  uint32    `protobuf:"varint,3,opt,name=vni,proto3" json:"vni,omitempty"`
	Lbports              []*LBPort `protobuf:"bytes,4,rep,name=lbports,proto3" json:"lbports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateLoadBalancerRequest) Reset()         { *m = CreateLoadBalancerRequest{} }
func (m *CreateLoadBalancerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLoadBalancerRequest) ProtoMessage()    {}
func (*CreateLoadBalancerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{23}
}

func (m *CreateLoadBalancerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLoadBalancerRequest.Unmarshal(m, b)
}
func (m *CreateLoadBalancerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLoadBalancerRequest.Marshal(b, m, deterministic)
}
func (m *CreateLoadBalancerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLoadBalancerRequest.Merge(m, src)
}
func (m *CreateLoadBalancerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLoadBalancerRequest.Size(m)
}
func (m *CreateLoadBalancerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLoadBalancerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLoadBalancerRequest proto.InternalMessageInfo

func (m *CreateLoadBalancerRequest) GetLoadBalancerID() []byte {
	if m != nil {
		return m.LoadBalancerID
	}
	return nil
}

func (m *CreateLoadBalancerRequest) GetLbVipIP() *LBIP {
	if m != nil {
		return m.LbVipIP
	}
	return nil
}

func (m *CreateLoadBalancerRequest) GetVni() uint32 {
	if m != nil {
		return m.Vni
	}
	return 0
}

func (m *CreateLoadBalancerRequest) GetLbports() []*LBPort {
	if m != nil {
		return m.Lbports
	}
	return nil
}

type AddLoadBalancerTargetRequest struct {
	LoadBalancerID       []byte   `protobuf:"bytes,1,opt,name=loadBalancerID,proto3" json:"loadBalancerID,omitempty"`
	TargetIP             *LBIP    `protobuf:"bytes,2,opt,name=targetIP,proto3" json:"targetIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddLoadBalancerTargetRequest) Reset()         { *m = AddLoadBalancerTargetRequest{} }
func (m *AddLoadBalancerTargetRequest) String() string { return proto.CompactTextString(m) }
func (*AddLoadBalancerTargetRequest) ProtoMessage()    {}
func (*AddLoadBalancerTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{24}
}

func (m *AddLoadBalancerTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddLoadBalancerTargetRequest.Unmarshal(m, b)
}
func (m *AddLoadBalancerTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddLoadBalancerTargetRequest.Marshal(b, m, deterministic)
}
func (m *AddLoadBalancerTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddLoadBalancerTargetRequest.Merge(m, src)
}
func (m *AddLoadBalancerTargetRequest) XXX_Size() int {
	return xxx_messageInfo_AddLoadBalancerTargetRequest.Size(m)
}
func (m *AddLoadBalancerTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddLoadBalancerTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddLoadBalancerTargetRequest proto.InternalMessageInfo

func (m *AddLoadBalancerTargetRequest) GetLoadBalancerID() []byte {
	if m != nil {
		return m.LoadBalancerID
	}
	return nil
}

func (m *AddLoadBalancerTargetRequest) GetTargetIP() *LBIP {
	if m != nil {
		return m.TargetIP
	}
	return nil
}

type DeleteLoadBalancerTargetRequest struct {
	LoadBalancerID       []byte   `protobuf:"bytes,1,opt,name=loadBalancerID,proto3" json:"loadBalancerID,omitempty"`
	TargetIP             *LBIP    `protobuf:"bytes,2,opt,name=targetIP,proto3" json:"targetIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLoadBalancerTargetRequest) Reset()         { *m = DeleteLoadBalancerTargetRequest{} }
func (m *DeleteLoadBalancerTargetRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLoadBalancerTargetRequest) ProtoMessage()    {}
func (*DeleteLoadBalancerTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{25}
}

func (m *DeleteLoadBalancerTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLoadBalancerTargetRequest.Unmarshal(m, b)
}
func (m *DeleteLoadBalancerTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLoadBalancerTargetRequest.Marshal(b, m, deterministic)
}
func (m *DeleteLoadBalancerTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLoadBalancerTargetRequest.Merge(m, src)
}
func (m *DeleteLoadBalancerTargetRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLoadBalancerTargetRequest.Size(m)
}
func (m *DeleteLoadBalancerTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLoadBalancerTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLoadBalancerTargetRequest proto.InternalMessageInfo

func (m *DeleteLoadBalancerTargetRequest) GetLoadBalancerID() []byte {
	if m != nil {
		return m.LoadBalancerID
	}
	return nil
}

func (m *DeleteLoadBalancerTargetRequest) GetTargetIP() *LBIP {
	if m != nil {
		return m.TargetIP
	}
	return nil
}

type InterfacesMsg struct {
	Interfaces           []*Interface `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InterfacesMsg) Reset()         { *m = InterfacesMsg{} }
func (m *InterfacesMsg) String() string { return proto.CompactTextString(m) }
func (*InterfacesMsg) ProtoMessage()    {}
func (*InterfacesMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{26}
}

func (m *InterfacesMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfacesMsg.Unmarshal(m, b)
}
func (m *InterfacesMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfacesMsg.Marshal(b, m, deterministic)
}
func (m *InterfacesMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfacesMsg.Merge(m, src)
}
func (m *InterfacesMsg) XXX_Size() int {
	return xxx_messageInfo_InterfacesMsg.Size(m)
}
func (m *InterfacesMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfacesMsg.DiscardUnknown(m)
}

var xxx_messageInfo_InterfacesMsg proto.InternalMessageInfo

func (m *InterfacesMsg) GetInterfaces() []*Interface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

type RuleIDMsg struct {
	RuleID               []byte   `protobuf:"bytes,1,opt,name=ruleID,proto3" json:"ruleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuleIDMsg) Reset()         { *m = RuleIDMsg{} }
func (m *RuleIDMsg) String() string { return proto.CompactTextString(m) }
func (*RuleIDMsg) ProtoMessage()    {}
func (*RuleIDMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{27}
}

func (m *RuleIDMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuleIDMsg.Unmarshal(m, b)
}
func (m *RuleIDMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuleIDMsg.Marshal(b, m, deterministic)
}
func (m *RuleIDMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleIDMsg.Merge(m, src)
}
func (m *RuleIDMsg) XXX_Size() int {
	return xxx_messageInfo_RuleIDMsg.Size(m)
}
func (m *RuleIDMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleIDMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RuleIDMsg proto.InternalMessageInfo

func (m *RuleIDMsg) GetRuleID() []byte {
	if m != nil {
		return m.RuleID
	}
	return nil
}

type ThrottlingConfigMsg struct {
	InterfaceID          *InterfaceIDMsg   `protobuf:"bytes,1,opt,name=interfaceID,proto3" json:"interfaceID,omitempty"`
	ThrottlingConfig     *ThrottlingConfig `protobuf:"bytes,2,opt,name=throttlingConfig,proto3" json:"throttlingConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ThrottlingConfigMsg) Reset()         { *m = ThrottlingConfigMsg{} }
func (m *ThrottlingConfigMsg) String() string { return proto.CompactTextString(m) }
func (*ThrottlingConfigMsg) ProtoMessage()    {}
func (*ThrottlingConfigMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{28}
}

func (m *ThrottlingConfigMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThrottlingConfigMsg.Unmarshal(m, b)
}
func (m *ThrottlingConfigMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThrottlingConfigMsg.Marshal(b, m, deterministic)
}
func (m *ThrottlingConfigMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThrottlingConfigMsg.Merge(m, src)
}
func (m *ThrottlingConfigMsg) XXX_Size() int {
	return xxx_messageInfo_ThrottlingConfigMsg.Size(m)
}
func (m *ThrottlingConfigMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ThrottlingConfigMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ThrottlingConfigMsg proto.InternalMessageInfo

func (m *ThrottlingConfigMsg) GetInterfaceID() *InterfaceIDMsg {
	if m != nil {
		return m.InterfaceID
	}
	return nil
}

func (m *ThrottlingConfigMsg) GetThrottlingConfig() *ThrottlingConfig {
	if m != nil {
		return m.ThrottlingConfig
	}
	return nil
}

type InterfacePrefixMsg struct {
	InterfaceID          *InterfaceIDMsg `protobuf:"bytes,1,opt,name=interfaceID,proto3" json:"interfaceID,omitempty"`
	Prefix               *Prefix         `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InterfacePrefixMsg) Reset()         { *m = InterfacePrefixMsg{} }
func (m *InterfacePrefixMsg) String() string { return proto.CompactTextString(m) }
func (*InterfacePrefixMsg) ProtoMessage()    {}
func (*InterfacePrefixMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{29}
}

func (m *InterfacePrefixMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfacePrefixMsg.Unmarshal(m, b)
}
func (m *InterfacePrefixMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfacePrefixMsg.Marshal(b, m, deterministic)
}
func (m *InterfacePrefixMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfacePrefixMsg.Merge(m, src)
}
func (m *InterfacePrefixMsg) XXX_Size() int {
	return xxx_messageInfo_InterfacePrefixMsg.Size(m)
}
func (m *InterfacePrefixMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfacePrefixMsg.DiscardUnknown(m)
}

var xxx_messageInfo_InterfacePrefixMsg proto.InternalMessageInfo

func (m *InterfacePrefixMsg) GetInterfaceID() *InterfaceIDMsg {
	if m != nil {
		return m.InterfaceID
	}
	return nil
}

func (m *InterfacePrefixMsg) GetPrefix() *Prefix {
	if m != nil {
		return m.Prefix
	}
	return nil
}

type PrefixesMsg struct {
	Prefixes             []*Prefix `protobuf:"bytes,1,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PrefixesMsg) Reset()         { *m = PrefixesMsg{} }
func (m *PrefixesMsg) String() string { return proto.CompactTextString(m) }
func (*PrefixesMsg) ProtoMessage()    {}
func (*PrefixesMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{30}
}

func (m *PrefixesMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrefixesMsg.Unmarshal(m, b)
}
func (m *PrefixesMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrefixesMsg.Marshal(b, m, deterministic)
}
func (m *PrefixesMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrefixesMsg.Merge(m, src)
}
func (m *PrefixesMsg) XXX_Size() int {
	return xxx_messageInfo_PrefixesMsg.Size(m)
}
func (m *PrefixesMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PrefixesMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PrefixesMsg proto.InternalMessageInfo

func (m *PrefixesMsg) GetPrefixes() []*Prefix {
	if m != nil {
		return m.Prefixes
	}
	return nil
}

type VNIMsg struct {
	Vni                  uint32   `protobuf:"varint,1,opt,name=vni,proto3" json:"vni,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VNIMsg) Reset()         { *m = VNIMsg{} }
func (m *VNIMsg) String() string { return proto.CompactTextString(m) }
func (*VNIMsg) ProtoMessage()    {}
func (*VNIMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{31}
}

func (m *VNIMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VNIMsg.Unmarshal(m, b)
}
func (m *VNIMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VNIMsg.Marshal(b, m, deterministic)
}
func (m *VNIMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VNIMsg.Merge(m, src)
}
func (m *VNIMsg) XXX_Size() int {
	return xxx_messageInfo_VNIMsg.Size(m)
}
func (m *VNIMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_VNIMsg.DiscardUnknown(m)
}

var xxx_messageInfo_VNIMsg proto.InternalMessageInfo

func (m *VNIMsg) GetVni() uint32 {
	if m != nil {
		return m.Vni
	}
	return 0
}

type VNIRouteMsg struct {
	Vni                  *VNIMsg  `protobuf:"bytes,1,opt,name=vni,proto3" json:"vni,omitempty"`
	Route                *Route   `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VNIRouteMsg) Reset()         { *m = VNIRouteMsg{} }
func (m *VNIRouteMsg) String() string { return proto.CompactTextString(m) }
func (*VNIRouteMsg) ProtoMessage()    {}
func (*VNIRouteMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{32}
}

func (m *VNIRouteMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VNIRouteMsg.Unmarshal(m, b)
}
func (m *VNIRouteMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VNIRouteMsg.Marshal(b, m, deterministic)
}
func (m *VNIRouteMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VNIRouteMsg.Merge(m, src)
}
func (m *VNIRouteMsg) XXX_Size() int {
	return xxx_messageInfo_VNIRouteMsg.Size(m)
}
func (m *VNIRouteMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_VNIRouteMsg.DiscardUnknown(m)
}

var xxx_messageInfo_VNIRouteMsg proto.InternalMessageInfo

func (m *VNIRouteMsg) GetVni() *VNIMsg {
	if m != nil {
		return m.Vni
	}
	return nil
}

func (m *VNIRouteMsg) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type RoutesMsg struct {
	Routes               []*Route `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoutesMsg) Reset()         { *m = RoutesMsg{} }
func (m *RoutesMsg) String() string { return proto.CompactTextString(m) }
func (*RoutesMsg) ProtoMessage()    {}
func (*RoutesMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{33}
}

func (m *RoutesMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutesMsg.Unmarshal(m, b)
}
func (m *RoutesMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutesMsg.Marshal(b, m, deterministic)
}
func (m *RoutesMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutesMsg.Merge(m, src)
}
func (m *RoutesMsg) XXX_Size() int {
	return xxx_messageInfo_RoutesMsg.Size(m)
}
func (m *RoutesMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutesMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RoutesMsg proto.InternalMessageInfo

func (m *RoutesMsg) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type FirewallRuleMsg struct {
	InterfaceID          []byte        `protobuf:"bytes,1,opt,name=interfaceID,proto3" json:"interfaceID,omitempty"`
	Rule                 *FirewallRule `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FirewallRuleMsg) Reset()         { *m = FirewallRuleMsg{} }
func (m *FirewallRuleMsg) String() string { return proto.CompactTextString(m) }
func (*FirewallRuleMsg) ProtoMessage()    {}
func (*FirewallRuleMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{34}
}

func (m *FirewallRuleMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirewallRuleMsg.Unmarshal(m, b)
}
func (m *FirewallRuleMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirewallRuleMsg.Marshal(b, m, deterministic)
}
func (m *FirewallRuleMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirewallRuleMsg.Merge(m, src)
}
func (m *FirewallRuleMsg) XXX_Size() int {
	return xxx_messageInfo_FirewallRuleMsg.Size(m)
}
func (m *FirewallRuleMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FirewallRuleMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FirewallRuleMsg proto.InternalMessageInfo

func (m *FirewallRuleMsg) GetInterfaceID() []byte {
	if m != nil {
		return m.InterfaceID
	}
	return nil
}

func (m *FirewallRuleMsg) GetRule() *FirewallRule {
	if m != nil {
		return m.Rule
	}
	return nil
}

type FirewallRulesMsg struct {
	Rules                []*FirewallRule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FirewallRulesMsg) Reset()         { *m = FirewallRulesMsg{} }
func (m *FirewallRulesMsg) String() string { return proto.CompactTextString(m) }
func (*FirewallRulesMsg) ProtoMessage()    {}
func (*FirewallRulesMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{35}
}

func (m *FirewallRulesMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirewallRulesMsg.Unmarshal(m, b)
}
func (m *FirewallRulesMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirewallRulesMsg.Marshal(b, m, deterministic)
}
func (m *FirewallRulesMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirewallRulesMsg.Merge(m, src)
}
func (m *FirewallRulesMsg) XXX_Size() int {
	return xxx_messageInfo_FirewallRulesMsg.Size(m)
}
func (m *FirewallRulesMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FirewallRulesMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FirewallRulesMsg proto.InternalMessageInfo

func (m *FirewallRulesMsg) GetRules() []*FirewallRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

type UUIDMsg struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUIDMsg) Reset()         { *m = UUIDMsg{} }
func (m *UUIDMsg) String() string { return proto.CompactTextString(m) }
func (*UUIDMsg) ProtoMessage()    {}
func (*UUIDMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{36}
}

func (m *UUIDMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUIDMsg.Unmarshal(m, b)
}
func (m *UUIDMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUIDMsg.Marshal(b, m, deterministic)
}
func (m *UUIDMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUIDMsg.Merge(m, src)
}
func (m *UUIDMsg) XXX_Size() int {
	return xxx_messageInfo_UUIDMsg.Size(m)
}
func (m *UUIDMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UUIDMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UUIDMsg proto.InternalMessageInfo

func (m *UUIDMsg) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type VirtualFunction struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Domain               uint32   `protobuf:"varint,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Bus                  uint32   `protobuf:"varint,3,opt,name=bus,proto3" json:"bus,omitempty"`
	Slot                 uint32   `protobuf:"varint,4,opt,name=slot,proto3" json:"slot,omitempty"`
	Function             uint32   `protobuf:"varint,5,opt,name=function,proto3" json:"function,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtualFunction) Reset()         { *m = VirtualFunction{} }
func (m *VirtualFunction) String() string { return proto.CompactTextString(m) }
func (*VirtualFunction) ProtoMessage()    {}
func (*VirtualFunction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{37}
}

func (m *VirtualFunction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualFunction.Unmarshal(m, b)
}
func (m *VirtualFunction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualFunction.Marshal(b, m, deterministic)
}
func (m *VirtualFunction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualFunction.Merge(m, src)
}
func (m *VirtualFunction) XXX_Size() int {
	return xxx_messageInfo_VirtualFunction.Size(m)
}
func (m *VirtualFunction) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualFunction.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualFunction proto.InternalMessageInfo

func (m *VirtualFunction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VirtualFunction) GetDomain() uint32 {
	if m != nil {
		return m.Domain
	}
	return 0
}

func (m *VirtualFunction) GetBus() uint32 {
	if m != nil {
		return m.Bus
	}
	return 0
}

func (m *VirtualFunction) GetSlot() uint32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *VirtualFunction) GetFunction() uint32 {
	if m != nil {
		return m.Function
	}
	return 0
}

type CreateInterfaceResponse struct {
	Response             *IpAdditionResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Vf                   *VirtualFunction    `protobuf:"bytes,2,opt,name=vf,proto3" json:"vf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateInterfaceResponse) Reset()         { *m = CreateInterfaceResponse{} }
func (m *CreateInterfaceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateInterfaceResponse) ProtoMessage()    {}
func (*CreateInterfaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{38}
}

func (m *CreateInterfaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInterfaceResponse.Unmarshal(m, b)
}
func (m *CreateInterfaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInterfaceResponse.Marshal(b, m, deterministic)
}
func (m *CreateInterfaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInterfaceResponse.Merge(m, src)
}
func (m *CreateInterfaceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateInterfaceResponse.Size(m)
}
func (m *CreateInterfaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInterfaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInterfaceResponse proto.InternalMessageInfo

func (m *CreateInterfaceResponse) GetResponse() *IpAdditionResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *CreateInterfaceResponse) GetVf() *VirtualFunction {
	if m != nil {
		return m.Vf
	}
	return nil
}

type Route struct {
	IpVersion            IPVersion `protobuf:"varint,1,opt,name=ipVersion,proto3,enum=dpdkonmetal.IPVersion" json:"ipVersion,omitempty"`
	Prefix               *Prefix   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	NexthopVNI           uint32    `protobuf:"varint,3,opt,name=nexthopVNI,proto3" json:"nexthopVNI,omitempty"`
	NexthopAddress       []byte    `protobuf:"bytes,4,opt,name=nexthopAddress,proto3" json:"nexthopAddress,omitempty"`
	Weight               uint32    `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a26ffc81af0230d, []int{39}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetIpVersion() IPVersion {
	if m != nil {
		return m.IpVersion
	}
	return IPVersion_IPv4
}

func (m *Route) GetPrefix() *Prefix {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *Route) GetNexthopVNI() uint32 {
	if m != nil {
		return m.NexthopVNI
	}
	return 0
}

func (m *Route) GetNexthopAddress() []byte {
	if m != nil {
		return m.NexthopAddress
	}
	return nil
}

func (m *Route) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterEnum("dpdkonmetal.InterfaceType", InterfaceType_name, InterfaceType_value)
	proto.RegisterEnum("dpdkonmetal.IPVersion", IPVersion_name, IPVersion_value)
	proto.RegisterEnum("dpdkonmetal.Protocol", Protocol_name, Protocol_value)
	proto.RegisterEnum("dpdkonmetal.TrafficDirection", TrafficDirection_name, TrafficDirection_value)
	proto.RegisterEnum("dpdkonmetal.FirewallAction", FirewallAction_name, FirewallAction_value)
	proto.RegisterType((*Status)(nil), "dpdkonmetal.Status")
	proto.RegisterType((*IpAdditionResponse)(nil), "dpdkonmetal.IpAdditionResponse")
	proto.RegisterType((*CreateLoadBalancerResponse)(nil), "dpdkonmetal.CreateLoadBalancerResponse")
	proto.RegisterType((*Empty)(nil), "dpdkonmetal.Empty")
	proto.RegisterType((*Prefix)(nil), "dpdkonmetal.Prefix")
	proto.RegisterType((*InitConfig)(nil), "dpdkonmetal.InitConfig")
	proto.RegisterType((*PXEConfig)(nil), "dpdkonmetal.PXEConfig")
	proto.RegisterType((*FirewallRule)(nil), "dpdkonmetal.FirewallRule")
	proto.RegisterType((*IPConfig)(nil), "dpdkonmetal.IPConfig")
	proto.RegisterType((*ThrottlingConfig)(nil), "dpdkonmetal.ThrottlingConfig")
	proto.RegisterType((*CreateInterfaceRequest)(nil), "dpdkonmetal.CreateInterfaceRequest")
	proto.RegisterType((*Interface)(nil), "dpdkonmetal.Interface")
	proto.RegisterType((*InterfaceIDMsg)(nil), "dpdkonmetal.InterfaceIDMsg")
	proto.RegisterType((*GetInterfaceResponse)(nil), "dpdkonmetal.GetInterfaceResponse")
	proto.RegisterType((*InterfaceVIPIP)(nil), "dpdkonmetal.InterfaceVIPIP")
	proto.RegisterType((*LBIP)(nil), "dpdkonmetal.LBIP")
	proto.RegisterType((*InterfaceVIPMsg)(nil), "dpdkonmetal.InterfaceVIPMsg")
	proto.RegisterType((*GetLoadBalancerRequest)(nil), "dpdkonmetal.GetLoadBalancerRequest")
	proto.RegisterType((*GetLoadBalancerTargetsRequest)(nil), "dpdkonmetal.GetLoadBalancerTargetsRequest")
	proto.RegisterType((*DeleteLoadBalancerRequest)(nil), "dpdkonmetal.DeleteLoadBalancerRequest")
	proto.RegisterType((*LBPort)(nil), "dpdkonmetal.LBPort")
	proto.RegisterType((*GetLoadBalancerTargetsResponse)(nil), "dpdkonmetal.GetLoadBalancerTargetsResponse")
	proto.RegisterType((*GetLoadBalancerResponse)(nil), "dpdkonmetal.GetLoadBalancerResponse")
	proto.RegisterType((*CreateLoadBalancerRequest)(nil), "dpdkonmetal.CreateLoadBalancerRequest")
	proto.RegisterType((*AddLoadBalancerTargetRequest)(nil), "dpdkonmetal.AddLoadBalancerTargetRequest")
	proto.RegisterType((*DeleteLoadBalancerTargetRequest)(nil), "dpdkonmetal.DeleteLoadBalancerTargetRequest")
	proto.RegisterType((*InterfacesMsg)(nil), "dpdkonmetal.InterfacesMsg")
	proto.RegisterType((*RuleIDMsg)(nil), "dpdkonmetal.RuleIDMsg")
	proto.RegisterType((*ThrottlingConfigMsg)(nil), "dpdkonmetal.ThrottlingConfigMsg")
	proto.RegisterType((*InterfacePrefixMsg)(nil), "dpdkonmetal.InterfacePrefixMsg")
	proto.RegisterType((*PrefixesMsg)(nil), "dpdkonmetal.PrefixesMsg")
	proto.RegisterType((*VNIMsg)(nil), "dpdkonmetal.VNIMsg")
	proto.RegisterType((*VNIRouteMsg)(nil), "dpdkonmetal.VNIRouteMsg")
	proto.RegisterType((*RoutesMsg)(nil), "dpdkonmetal.RoutesMsg")
	proto.RegisterType((*FirewallRuleMsg)(nil), "dpdkonmetal.FirewallRuleMsg")
	proto.RegisterType((*FirewallRulesMsg)(nil), "dpdkonmetal.FirewallRulesMsg")
	proto.RegisterType((*UUIDMsg)(nil), "dpdkonmetal.UUIDMsg")
	proto.RegisterType((*VirtualFunction)(nil), "dpdkonmetal.VirtualFunction")
	proto.RegisterType((*CreateInterfaceResponse)(nil), "dpdkonmetal.CreateInterfaceResponse")
	proto.RegisterType((*Route)(nil), "dpdkonmetal.Route")
}

func init() { proto.RegisterFile("proto/dpdk.proto", fileDescriptor_8a26ffc81af0230d) }

var fileDescriptor_8a26ffc81af0230d = []byte{
	// 2211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x59, 0x5b, 0x73, 0xdb, 0xc6,
	0xf5, 0x17, 0x78, 0x13, 0x79, 0x28, 0x4a, 0xf4, 0x5a, 0xa2, 0x69, 0x46, 0x8e, 0xf5, 0xdf, 0xe4,
	0xef, 0xaa, 0x92, 0x2d, 0xb7, 0x8a, 0xab, 0xa4, 0x71, 0x93, 0x46, 0xa2, 0x24, 0x07, 0x53, 0xc9,
	0x46, 0xa0, 0xcb, 0xa4, 0x7d, 0x48, 0x07, 0x22, 0x96, 0x14, 0xc6, 0x10, 0x80, 0x02, 0x20, 0x2d,
	0xf5, 0xa1, 0xed, 0x43, 0x5e, 0xfb, 0x15, 0xda, 0x97, 0x3e, 0x67, 0xa6, 0x33, 0xfd, 0x0e, 0x9d,
	0xe9, 0xd7, 0xe8, 0x43, 0xbf, 0x46, 0x67, 0x2f, 0x00, 0xb1, 0x20, 0x40, 0x5d, 0x26, 0xcd, 0x13,
	0xb1, 0xbb, 0xbf, 0x73, 0xd9, 0xb3, 0xe7, 0x9c, 0x3d, 0x67, 0x09, 0x4d, 0xcf, 0x77, 0x43, 0xf7,
	0xb9, 0xe9, 0x99, 0x6f, 0x37, 0xd8, 0x27, 0xaa, 0xd3, 0x6f, 0xd7, 0xb9, 0x20, 0xa1, 0x61, 0xe3,
	0x4f, 0xa0, 0x72, 0x14, 0x1a, 0xe1, 0x30, 0x40, 0x8b, 0x50, 0x26, 0xbe, 0xef, 0xfa, 0x6d, 0x65,
	0x45, 0x59, 0x2d, 0xeb, 0x7c, 0x80, 0xda, 0x30, 0x7b, 0x41, 0x82, 0xc0, 0x18, 0x90, 0x76, 0x61,
	0x45, 0x59, 0xad, 0xe9, 0xd1, 0x10, 0x0f, 0x00, 0xa9, 0xde, 0xb6, 0x69, 0x5a, 0xa1, 0xe5, 0x3a,
	0x3a, 0x09, 0x3c, 0xd7, 0x09, 0x08, 0x5a, 0x87, 0x4a, 0xc0, 0xf8, 0x31, 0x36, 0xf5, 0xcd, 0xfb,
	0x1b, 0x09, 0x69, 0x1b, 0x5c, 0x94, 0x2e, 0x20, 0xe8, 0x43, 0x68, 0x0c, 0x1d, 0x93, 0xf8, 0xb6,
	0x71, 0xa5, 0xbb, 0xc3, 0x90, 0x8b, 0x98, 0xd3, 0xe5, 0x49, 0xec, 0x42, 0xa7, 0xeb, 0x13, 0x23,
	0x24, 0x07, 0xae, 0x61, 0xee, 0x18, 0xb6, 0xe1, 0xf4, 0x88, 0xff, 0xbf, 0x14, 0x38, 0x0b, 0xe5,
	0xbd, 0x0b, 0x2f, 0xbc, 0xc2, 0xdf, 0x29, 0x50, 0xd1, 0x7c, 0xd2, 0xb7, 0x2e, 0xd1, 0x0b, 0xa8,
	0x59, 0xde, 0x29, 0xf1, 0x03, 0xcb, 0x75, 0x98, 0xa4, 0xf9, 0xcd, 0x96, 0x24, 0x49, 0xd5, 0xc4,
	0xaa, 0x3e, 0x06, 0x52, 0xeb, 0x19, 0xa6, 0xe9, 0x93, 0x20, 0x10, 0x92, 0xa2, 0x21, 0xc2, 0x30,
	0xe7, 0x31, 0xce, 0x07, 0xc4, 0x19, 0x84, 0xe7, 0xed, 0xe2, 0x8a, 0xb2, 0xda, 0xd0, 0xa5, 0x39,
	0xf4, 0x13, 0xb8, 0x6f, 0x27, 0xb6, 0xbc, 0xe7, 0x18, 0x67, 0x36, 0x31, 0xdb, 0xa5, 0x15, 0x65,
	0xb5, 0xaa, 0x67, 0x2d, 0xe1, 0x3f, 0x2b, 0x00, 0xaa, 0x63, 0x85, 0x5d, 0xd7, 0xe9, 0x5b, 0x03,
	0xd4, 0x05, 0x14, 0xed, 0x4c, 0xd5, 0x46, 0x5b, 0x7c, 0x2b, 0x99, 0x76, 0xe2, 0x4b, 0x7a, 0x06,
	0x1c, 0xad, 0x40, 0x7d, 0xe8, 0xd9, 0x96, 0xf3, 0x56, 0x73, 0xfd, 0x90, 0xee, 0xa3, 0xb8, 0x5a,
	0xd3, 0x93, 0x53, 0x74, 0x97, 0x5e, 0xff, 0xb5, 0x71, 0x41, 0x82, 0x76, 0x91, 0xad, 0x46, 0x43,
	0xfc, 0x06, 0x6a, 0xda, 0xd7, 0x7b, 0x42, 0x9b, 0xf7, 0x01, 0x1c, 0x72, 0x19, 0x1e, 0x11, 0x7f,
	0x44, 0xb8, 0x97, 0xd5, 0xf4, 0xc4, 0x0c, 0x35, 0xc9, 0x99, 0xeb, 0x86, 0xfb, 0x96, 0x4d, 0x28,
	0xb5, 0xf0, 0x37, 0x69, 0x0e, 0xff, 0xb3, 0x0c, 0x73, 0xfb, 0x96, 0x4f, 0xde, 0x19, 0xb6, 0xad,
	0x0f, 0x6d, 0x82, 0x5a, 0x50, 0xf1, 0x87, 0x36, 0x51, 0x77, 0x19, 0xc3, 0x39, 0x5d, 0x8c, 0xd0,
	0x53, 0xb8, 0x67, 0x39, 0x01, 0xf1, 0xc3, 0xed, 0x7e, 0x48, 0x7c, 0x9d, 0x43, 0xf8, 0x19, 0x4c,
	0x2e, 0xa0, 0x97, 0x50, 0x33, 0x2d, 0x9f, 0xf4, 0xa8, 0x2b, 0xb3, 0xa3, 0x98, 0xdf, 0x7c, 0x24,
	0xd9, 0xe7, 0xd8, 0x37, 0xfa, 0x7d, 0xab, 0xb7, 0x1b, 0x81, 0xf4, 0x31, 0x1e, 0x7d, 0x04, 0x15,
	0x83, 0x53, 0x96, 0x18, 0xe5, 0x7b, 0x12, 0x65, 0xa4, 0xed, 0x36, 0xa7, 0x13, 0x50, 0xd9, 0x9f,
	0xca, 0x37, 0xf5, 0xa7, 0x8f, 0x61, 0x2e, 0x70, 0x87, 0x7e, 0x8f, 0x88, 0xa3, 0xac, 0xe4, 0x1f,
	0xa5, 0x04, 0x44, 0xdb, 0x70, 0xcf, 0x24, 0x41, 0x68, 0x39, 0x06, 0x95, 0x2e, 0xa8, 0x67, 0xf3,
	0xa9, 0x27, 0xd1, 0xe8, 0xa7, 0x50, 0x65, 0xf9, 0xa3, 0xe7, 0xda, 0xed, 0x2a, 0x53, 0x78, 0x29,
	0x45, 0xc9, 0x17, 0xf5, 0x18, 0x86, 0x36, 0x61, 0x51, 0x68, 0xe1, 0xfa, 0xa1, 0x6e, 0x38, 0x03,
	0x72, 0xe0, 0xbe, 0x23, 0x7e, 0xbb, 0xc6, 0x32, 0x4c, 0xe6, 0x5a, 0x06, 0xcd, 0x89, 0xe7, 0x11,
	0xbf, 0x0d, 0x99, 0x34, 0x6c, 0x0d, 0xfd, 0x02, 0x1e, 0x26, 0xf5, 0x95, 0x85, 0xd5, 0x19, 0x61,
	0x3e, 0x20, 0x8f, 0x9a, 0x8b, 0x9d, 0xcb, 0xa7, 0xe6, 0xb2, 0x3b, 0x50, 0xb5, 0x7a, 0x17, 0x5e,
	0xd7, 0x35, 0x49, 0xbb, 0xc1, 0xc0, 0xf1, 0x38, 0x5a, 0x3b, 0xbe, 0xf2, 0x48, 0x7b, 0x7e, 0xbc,
	0x46, 0xc7, 0xf8, 0x6f, 0x45, 0xa8, 0xaa, 0x9a, 0x08, 0x8d, 0xbb, 0x65, 0x97, 0x27, 0x30, 0xef,
	0xf9, 0xd6, 0x85, 0xe1, 0x5f, 0x6d, 0x4b, 0x49, 0x26, 0x35, 0x8b, 0x9a, 0x50, 0xbc, 0x08, 0x87,
	0x22, 0xc5, 0xd0, 0x4f, 0x1a, 0x6a, 0xe6, 0x79, 0xcf, 0xfb, 0xd2, 0x0d, 0x42, 0x87, 0x86, 0x5a,
	0x89, 0x87, 0x5a, 0x72, 0x8e, 0x72, 0xa7, 0xe3, 0x5d, 0xf7, 0xc2, 0xb0, 0x1c, 0x86, 0x2a, 0x33,
	0x54, 0x6a, 0x96, 0xea, 0xee, 0x5d, 0x12, 0xbe, 0x11, 0xe1, 0x90, 0xb2, 0xee, 0x71, 0x06, 0xd0,
	0xc7, 0x40, 0xaa, 0x93, 0x13, 0x7a, 0xed, 0x59, 0x96, 0x2f, 0xe8, 0x27, 0x9d, 0x31, 0x9d, 0xa0,
	0x5d, 0x5d, 0x29, 0xae, 0xce, 0xe9, 0xf4, 0x13, 0xfd, 0x12, 0x1a, 0xfd, 0x44, 0xac, 0x07, 0xed,
	0xda, 0x4a, 0x71, 0xb5, 0xbe, 0xf9, 0x30, 0x33, 0xbe, 0x28, 0x42, 0x97, 0xf1, 0xd4, 0xeb, 0x2d,
	0x27, 0x24, 0x7e, 0xdf, 0x88, 0x02, 0x81, 0x04, 0x6d, 0x60, 0x4c, 0xb2, 0xbd, 0x7e, 0x02, 0x8d,
	0xff, 0x52, 0x80, 0xe6, 0xf1, 0xb9, 0xef, 0x86, 0xa1, 0x6d, 0x39, 0x03, 0xa1, 0xfc, 0x27, 0xf0,
	0xc0, 0x72, 0x06, 0xd4, 0xb6, 0x9a, 0xd1, 0x7b, 0x4b, 0xc2, 0x40, 0x23, 0xfe, 0x11, 0xe9, 0xb9,
	0x8e, 0xc9, 0x0e, 0xaf, 0xa1, 0xe7, 0x2d, 0xa3, 0x4f, 0xa1, 0x2d, 0x96, 0x0e, 0xc9, 0xc0, 0x38,
	0xb3, 0x92, 0xa4, 0x05, 0x46, 0x9a, 0xbb, 0x8e, 0xb6, 0xa0, 0x45, 0xb2, 0x85, 0xf2, 0x93, 0xcd,
	0x59, 0xa5, 0xda, 0x92, 0x1c, 0x91, 0x25, 0xae, 0x6d, 0xce, 0x32, 0x75, 0x93, 0x0b, 0xe3, 0xf2,
	0x8d, 0x47, 0x9c, 0x7d, 0xdb, 0x7d, 0x17, 0x30, 0x07, 0x68, 0xe8, 0xd2, 0x1c, 0xfe, 0x4f, 0x01,
	0x5a, 0xfc, 0x7a, 0x56, 0x23, 0xe3, 0xe9, 0xe4, 0x77, 0x43, 0x12, 0x84, 0xe8, 0x0b, 0x68, 0xc4,
	0x06, 0x65, 0x31, 0xc0, 0x3d, 0xbb, 0x23, 0x7b, 0x76, 0x12, 0xa1, 0xcb, 0x04, 0xf4, 0xee, 0x89,
	0x27, 0xe2, 0xfc, 0x9d, 0x9c, 0xa2, 0x5e, 0x33, 0x72, 0xac, 0xc8, 0xb7, 0x47, 0x8e, 0x85, 0x7e,
	0x06, 0x60, 0x79, 0xa3, 0x17, 0xc2, 0x21, 0x4b, 0xcc, 0x21, 0x97, 0x52, 0xc1, 0x24, 0xfc, 0x31,
	0x01, 0x14, 0x64, 0x5b, 0x82, 0xac, 0x7c, 0x1d, 0xd9, 0xd6, 0xf8, 0x52, 0x33, 0xc9, 0xc8, 0xea,
	0xf1, 0x2b, 0xab, 0xc2, 0x2f, 0xb5, 0xf1, 0x0c, 0x52, 0xa1, 0x19, 0xa6, 0xdc, 0x47, 0xe4, 0xdd,
	0xd4, 0x05, 0x93, 0x02, 0xe9, 0x13, 0x64, 0xf8, 0xbb, 0x02, 0xd4, 0x62, 0x6b, 0xa5, 0x4d, 0xa3,
	0xe4, 0x9a, 0xa6, 0x30, 0x36, 0xcd, 0x06, 0x20, 0x91, 0x1a, 0x54, 0x6d, 0xf4, 0x22, 0x4a, 0x1a,
	0x45, 0x46, 0x9a, 0xb1, 0x22, 0xe3, 0xb7, 0x22, 0x7c, 0x29, 0x8d, 0x8f, 0x56, 0x32, 0x37, 0x5b,
	0xbe, 0xd3, 0x66, 0x27, 0x2b, 0xb5, 0x4a, 0x46, 0xa5, 0x86, 0x96, 0xa1, 0xe6, 0xf5, 0xac, 0x5d,
	0x8f, 0x19, 0x7f, 0x96, 0x19, 0x7f, 0x3c, 0x81, 0x37, 0x61, 0x5e, 0x1d, 0xdb, 0xe3, 0x30, 0x18,
	0x5c, 0x6f, 0x34, 0x7c, 0x05, 0x8b, 0xaf, 0x48, 0x98, 0x70, 0xe5, 0xbb, 0x94, 0x99, 0x34, 0x9d,
	0x47, 0x1c, 0x98, 0xfd, 0xd3, 0x29, 0x71, 0xcc, 0x7f, 0x0c, 0xa4, 0xc5, 0xdb, 0x58, 0xdf, 0x53,
	0x55, 0x53, 0xb5, 0xdb, 0x4b, 0x8d, 0x2f, 0x91, 0xc2, 0x1d, 0x4a, 0xd4, 0xa2, 0x54, 0xa2, 0xe2,
	0x53, 0x28, 0x1d, 0xec, 0xa8, 0xda, 0xf7, 0x5d, 0xfa, 0xe2, 0x4b, 0x58, 0x48, 0x6e, 0xf3, 0x46,
	0xe7, 0x82, 0xba, 0x30, 0x6f, 0x49, 0xb6, 0x11, 0x76, 0x7d, 0x2f, 0xdb, 0xae, 0x0c, 0xa2, 0xa7,
	0x48, 0xf0, 0x17, 0xd0, 0x7a, 0x45, 0x42, 0xb9, 0x8d, 0xe0, 0xa9, 0xea, 0x09, 0xcc, 0x27, 0xeb,
	0xe9, 0x58, 0x87, 0xd4, 0x2c, 0x7e, 0x05, 0x8f, 0x52, 0x1c, 0x8e, 0x0d, 0x7f, 0x40, 0xc2, 0xe0,
	0xb6, 0x8c, 0xba, 0xf0, 0x70, 0x97, 0xd8, 0x24, 0xdd, 0xd4, 0xdc, 0x8e, 0xc9, 0x1b, 0xa8, 0x1c,
	0xec, 0xd0, 0x7a, 0x04, 0x21, 0x28, 0x79, 0xae, 0x1f, 0x8a, 0xeb, 0x87, 0x7d, 0x4b, 0x05, 0x5b,
	0xe1, 0x46, 0x05, 0x1b, 0xfe, 0x03, 0xbc, 0x9f, 0xb7, 0xbd, 0xbb, 0xc4, 0xc1, 0x73, 0xa8, 0x85,
	0x8c, 0x5e, 0xd5, 0x78, 0xe3, 0x50, 0xdf, 0xbc, 0x27, 0xe1, 0xa9, 0x7f, 0xe9, 0x63, 0x0c, 0xfe,
	0x87, 0x02, 0x0f, 0x26, 0x4e, 0xe8, 0x2e, 0x92, 0xd7, 0x61, 0xd6, 0x3e, 0x3b, 0xb5, 0xbc, 0xd8,
	0x4f, 0x32, 0xe4, 0x46, 0x88, 0x8c, 0x3b, 0xe4, 0x19, 0x25, 0xf7, 0x58, 0xbf, 0x53, 0xca, 0x28,
	0x17, 0xb8, 0xd1, 0xf5, 0x08, 0x83, 0xff, 0xae, 0xc0, 0xc3, 0xac, 0x16, 0xf5, 0x56, 0xa7, 0xf9,
	0x03, 0xeb, 0x3c, 0x84, 0xe5, 0x6d, 0xd3, 0x9c, 0x3c, 0xea, 0xdb, 0x6a, 0xfd, 0x0c, 0xaa, 0xd1,
	0xf9, 0xe5, 0xab, 0x1d, 0x43, 0xf0, 0x25, 0x3c, 0x9e, 0xf4, 0xfb, 0x1f, 0x44, 0xf2, 0x2b, 0x68,
	0xc4, 0xe9, 0x21, 0xa0, 0x49, 0x67, 0x0b, 0x20, 0xce, 0x0f, 0xd4, 0xa9, 0x8a, 0x53, 0xd2, 0x74,
	0x02, 0x89, 0x3f, 0x80, 0x1a, 0x6f, 0x1b, 0x29, 0x93, 0x9c, 0xfe, 0x13, 0xff, 0x55, 0x81, 0xfb,
	0xe9, 0x6b, 0x8e, 0xe2, 0x3f, 0x9b, 0xcc, 0x74, 0xb9, 0x49, 0x8c, 0x49, 0x90, 0xd3, 0x60, 0xd6,
	0x0d, 0x5b, 0xb8, 0x5b, 0x39, 0xf1, 0x27, 0x05, 0x90, 0x2a, 0xd7, 0xbb, 0xdf, 0x83, 0x82, 0xeb,
	0x50, 0xe1, 0x6f, 0x18, 0x42, 0xad, 0xcc, 0x3a, 0x5b, 0x40, 0xf0, 0xe7, 0x50, 0x8f, 0x0a, 0x6d,
	0x2a, 0xfa, 0x39, 0x4d, 0x58, 0xa2, 0x4a, 0x57, 0xf2, 0xab, 0xf4, 0x18, 0x84, 0x3b, 0x50, 0x39,
	0x7d, 0xad, 0x52, 0x52, 0x11, 0x0e, 0x4a, 0x1c, 0x0e, 0xf8, 0x1b, 0xa8, 0x9f, 0xbe, 0x56, 0x59,
	0x99, 0x40, 0x01, 0xff, 0x3f, 0x06, 0xa4, 0xd9, 0x72, 0x16, 0x3c, 0x88, 0x56, 0xa1, 0xec, 0xc7,
	0x0f, 0x43, 0xf5, 0x4d, 0x24, 0x01, 0x19, 0x33, 0x9d, 0x03, 0xf0, 0xc7, 0x50, 0x63, 0x63, 0xa6,
	0xf9, 0x1a, 0x54, 0xd8, 0x6c, 0xa4, 0x77, 0x16, 0x9d, 0x40, 0xe0, 0x33, 0x58, 0x48, 0xf6, 0x2c,
	0x37, 0xbb, 0xfe, 0x9e, 0x41, 0x89, 0x3a, 0x96, 0x50, 0x6b, 0x4a, 0x07, 0xc4, 0x60, 0xb8, 0x0b,
	0xcd, 0xe4, 0xac, 0xb0, 0x6e, 0xd9, 0x67, 0x5d, 0x94, 0x72, 0x5d, 0x17, 0xc5, 0x71, 0xf8, 0x11,
	0xcc, 0x9e, 0x9c, 0x70, 0x2f, 0x47, 0x50, 0x1a, 0x0e, 0x2d, 0x53, 0x3c, 0xda, 0xb0, 0x6f, 0xfc,
	0x47, 0x58, 0x38, 0xb5, 0xfc, 0x70, 0x68, 0xd8, 0xfb, 0x43, 0x87, 0x3f, 0x6a, 0x20, 0x28, 0xb1,
	0x46, 0x51, 0xc0, 0x58, 0x7b, 0xd8, 0x82, 0x8a, 0xc9, 0x9a, 0x45, 0x51, 0x88, 0x8a, 0x11, 0x3d,
	0xb1, 0xb3, 0x61, 0x10, 0x25, 0xb0, 0xb3, 0x61, 0x40, 0xa9, 0x03, 0xdb, 0x0d, 0x45, 0x53, 0xc2,
	0xbe, 0x69, 0x07, 0xdd, 0x17, 0xdc, 0x45, 0xf7, 0x11, 0x8f, 0xf1, 0xb7, 0x0a, 0x3c, 0x98, 0xe8,
	0x3c, 0xc4, 0x65, 0xf1, 0x12, 0xaa, 0xbe, 0xf8, 0x16, 0x67, 0xfe, 0x58, 0x76, 0xe1, 0x89, 0x97,
	0x4b, 0x3d, 0x26, 0x40, 0x4f, 0xa1, 0x30, 0xea, 0x0b, 0x53, 0x2f, 0xcb, 0xae, 0x22, 0x6f, 0x58,
	0x2f, 0x8c, 0xfa, 0xf8, 0x5f, 0x0a, 0x94, 0x79, 0x35, 0x7a, 0xb7, 0x42, 0xe9, 0x36, 0x11, 0x13,
	0xbd, 0xa1, 0x9d, 0xbb, 0xde, 0xe9, 0x6b, 0x55, 0x18, 0x2f, 0x31, 0x43, 0x73, 0xa7, 0x18, 0xc9,
	0xd5, 0x7a, 0x6a, 0x96, 0x9e, 0xca, 0x3b, 0x62, 0x0d, 0xce, 0x43, 0x61, 0x55, 0x31, 0x5a, 0xfb,
	0x2c, 0x91, 0x24, 0x59, 0x07, 0xb6, 0x08, 0x4d, 0xb1, 0xe9, 0x78, 0xbe, 0x39, 0x83, 0x5a, 0x80,
	0x76, 0x0c, 0x9f, 0x1c, 0x52, 0x15, 0xc7, 0xf3, 0xca, 0xda, 0x63, 0xa8, 0xc5, 0x7b, 0x44, 0x55,
	0x28, 0xd1, 0x66, 0xa2, 0x39, 0x23, 0xbe, 0xb6, 0x9a, 0xca, 0xda, 0x01, 0x54, 0xa3, 0xb2, 0x03,
	0x35, 0xa0, 0x76, 0xe2, 0x98, 0xa4, 0x6f, 0x39, 0xc4, 0x14, 0xa0, 0xee, 0xa1, 0xd6, 0x54, 0xd0,
	0x2c, 0x14, 0x8f, 0xbb, 0x5a, 0xb3, 0x42, 0x3f, 0x4e, 0x76, 0xb5, 0xe6, 0x3d, 0x04, 0x50, 0xa1,
	0x6b, 0xa3, 0xad, 0xe6, 0xa7, 0xa8, 0x06, 0xa5, 0xa3, 0xee, 0xb1, 0xd6, 0xfc, 0x56, 0x59, 0x5b,
	0x87, 0x66, 0xfa, 0x61, 0x0e, 0xd5, 0x61, 0x56, 0xe5, 0x1d, 0x74, 0x73, 0x86, 0xd2, 0xed, 0xf1,
	0x6f, 0x65, 0xed, 0x09, 0xcc, 0xcb, 0x6f, 0x71, 0x54, 0xe2, 0xae, 0xef, 0x7a, 0x1c, 0xb7, 0xdd,
	0xeb, 0x11, 0x2f, 0x6c, 0x2a, 0x9b, 0xff, 0x5e, 0x80, 0xfa, 0xae, 0xb6, 0xfb, 0x2b, 0x71, 0x02,
	0xe8, 0xe7, 0x34, 0x38, 0xad, 0xd0, 0x32, 0x6c, 0xeb, 0xf7, 0xc4, 0x44, 0x72, 0x68, 0xb3, 0x77,
	0xe2, 0xce, 0xa2, 0x34, 0x27, 0x82, 0x06, 0xcf, 0xa0, 0x2d, 0x28, 0x51, 0x52, 0xf4, 0x20, 0x95,
	0x3e, 0xa3, 0x07, 0xda, 0x4e, 0x56, 0x0d, 0x83, 0x67, 0xd0, 0x0e, 0xcc, 0xdb, 0x56, 0x30, 0xee,
	0x42, 0x82, 0x4c, 0xa9, 0x39, 0x7d, 0x74, 0xc0, 0x65, 0x6b, 0x30, 0x37, 0x48, 0x34, 0x32, 0x68,
	0x5a, 0x0a, 0xef, 0xfc, 0x9f, 0xb4, 0x98, 0xd5, 0x00, 0xe1, 0x19, 0xf4, 0x0d, 0x2c, 0xf4, 0xe4,
	0x70, 0x43, 0x1f, 0x48, 0x74, 0xd9, 0xcf, 0x00, 0x9d, 0x0f, 0xa7, 0x83, 0x62, 0xfe, 0x7b, 0xb0,
	0x60, 0xb2, 0xd2, 0xe0, 0x86, 0x4a, 0xe7, 0x18, 0xef, 0x2b, 0x68, 0x0d, 0x3d, 0xd3, 0x08, 0xc9,
	0xc4, 0xb3, 0xcd, 0xca, 0xd4, 0x2b, 0x72, 0x0a, 0x4b, 0x0d, 0x96, 0xa4, 0xf3, 0x88, 0x2e, 0xad,
	0xe9, 0xfa, 0xb5, 0x33, 0x02, 0x39, 0x3a, 0x9d, 0xaf, 0x01, 0x19, 0xa6, 0x99, 0x62, 0x88, 0x1e,
	0x67, 0xb3, 0x8b, 0x2f, 0xe7, 0xce, 0x75, 0x49, 0x0c, 0xcf, 0xa0, 0x37, 0xb0, 0x94, 0xb2, 0xe2,
	0x4d, 0x99, 0xe7, 0x6c, 0x5e, 0x87, 0x85, 0xa4, 0xaa, 0xa7, 0xaa, 0x86, 0x96, 0x73, 0x9b, 0xae,
	0x1b, 0x2a, 0x79, 0x08, 0x0b, 0x49, 0xe7, 0xa4, 0x3c, 0xa7, 0x9a, 0x72, 0x5a, 0x97, 0x87, 0x67,
	0xd0, 0x97, 0x80, 0x52, 0x7b, 0xbe, 0x96, 0x63, 0xce, 0x66, 0x07, 0x80, 0x7a, 0x13, 0x85, 0x3c,
	0x7a, 0x92, 0xe1, 0xc1, 0x19, 0x95, 0x7e, 0xe7, 0x47, 0xd7, 0xe2, 0x92, 0xc1, 0x34, 0x90, 0x1b,
	0x9d, 0x54, 0x30, 0x65, 0x37, 0xaa, 0xa9, 0x60, 0xca, 0xe9, 0x95, 0xf0, 0x0c, 0x3a, 0x8a, 0x4c,
	0x32, 0x65, 0x23, 0xb9, 0x0d, 0x68, 0x9e, 0x75, 0x7e, 0x0d, 0x4b, 0x46, 0x56, 0xcf, 0x80, 0x7e,
	0x2c, 0xe1, 0xa7, 0xf5, 0x15, 0x79, 0xac, 0x03, 0x68, 0x0d, 0x32, 0x3b, 0x4f, 0xb4, 0x36, 0x6d,
	0xc7, 0x72, 0xf7, 0xdd, 0x59, 0xbf, 0x11, 0x36, 0x36, 0xd2, 0x6f, 0xa1, 0x6d, 0xe6, 0x34, 0x23,
	0xe8, 0xe9, 0x35, 0xa6, 0xba, 0xd1, 0xae, 0x5e, 0x02, 0xd0, 0xc4, 0xc1, 0x0b, 0x45, 0x94, 0x55,
	0x76, 0x76, 0x5a, 0x93, 0xa5, 0xa2, 0xc8, 0x11, 0x2f, 0xa1, 0x6a, 0x98, 0x26, 0x2f, 0x2d, 0xda,
	0x69, 0xd2, 0xa8, 0xb0, 0xcd, 0x93, 0xfc, 0x39, 0xd4, 0xf9, 0xd6, 0xee, 0x48, 0xff, 0x15, 0xdc,
	0xa3, 0x9a, 0x4b, 0x55, 0xe4, 0xf4, 0x88, 0x7a, 0x94, 0x5b, 0x50, 0x8a, 0xfd, 0xec, 0xb3, 0x44,
	0x22, 0xfd, 0x7b, 0xb7, 0x9c, 0x4b, 0x33, 0x45, 0xb5, 0x6e, 0xe4, 0xda, 0xf2, 0x1f, 0x81, 0xb2,
	0x1d, 0xa3, 0x06, 0x2d, 0x87, 0xc9, 0x4e, 0xe3, 0x37, 0xf5, 0x0d, 0xf6, 0xa7, 0x38, 0x7b, 0xfb,
	0x38, 0xab, 0xb0, 0x9f, 0x8f, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x9f, 0x29, 0x2c, 0x2e,
	0x1f, 0x00, 0x00,
}
