name: Lint Golang Codebase

on:
  pull_request_target:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
jobs:
  golangci:
    name: lint
    runs-on: self-hosted
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
