name: test

on:
  ##push:
  ##  branches:
  ##    - feature/automated_testing
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Go Environment
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Run dp-service
        run: docker run --rm --entrypoint ./dp_service.py --privileged -p1337:1337 --mount type=bind,source=/dev/hugepages,target=/dev/hugepages ghcr.io/onmetal/dp-service-tester --no-init &

      - run: make test
      - name: Cleanup services
        if: always()
        run: |
          for i in $(docker ps -q); do docker stop $i; done
      - name: Cleanup services
        if: always()
        run: |
          for i in $(docker ps -q); do docker stop $i; done
