name: test

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  checks:
    name: run
    runs-on: [ self-hosted, dpdk ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run dpservice
        run: docker run --rm --entrypoint ./dp_service.py --privileged -p1337:1337 --mount type=bind,source=/dev/hugepages,target=/dev/hugepages ghcr.io/ironcore-dev/dpservice-tester:main --no-init &
      - name: Run wait for tcp port
        run: timeout 10 bash -c 'until echo > /dev/tcp/localhost/1337 2>/dev/null; do sleep 1; done' 2>/dev/null
      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - run: make test
      - name: Cleanup services
        if: always()
        run: |
          for i in $(docker ps -q); do docker stop $i; done
